import { AlertLog } from '../types';

export const mockAlerts: AlertLog[] = [
  // Active alerts
  {
    id: 'alt-001',
    deviceId: 'dev-drip-103',
    deviceName: 'HF-DRP-Gamma',
    sensorType: 'waterLevel',
    severity: 'critical',
    message: 'Water reservoir level is critical (35%). Drip pump runs suspended to prevent pump burnout.',
    value: 35,
    timestamp: '2026-07-15T11:45:00Z',
    resolved: false,
  },
  {
    id: 'alt-002',
    deviceId: 'dev-drip-103',
    deviceName: 'HF-DRP-Gamma',
    sensorType: 'ph',
    severity: 'warning',
    message: 'pH level is elevated at 6.8 (Target: 5.5 - 6.5). Nutrient absorption may be compromised.',
    value: 6.8,
    timestamp: '2026-07-15T12:10:00Z',
    resolved: false,
  },
  {
    id: 'alt-003',
    deviceId: 'dev-aero-104',
    deviceName: 'HF-AER-Delta',
    sensorType: 'connection',
    severity: 'info',
    message: 'Device set to MAINTENANCE mode. Scheduled misting suspended.',
    timestamp: '2026-07-15T10:45:00Z',
    resolved: false,
  },
  // Resolved historical alerts
  {
    id: 'alt-004',
    deviceId: 'dev-nft-101',
    deviceName: 'HF-NFT-Alpha',
    sensorType: 'ph',
    severity: 'warning',
    message: 'pH dipped to 5.2 (Threshold: 5.5). Auto dosing pump triggered.',
    value: 5.2,
    timestamp: '2026-07-14T14:20:00Z',
    resolved: true,
    resolvedAt: '2026-07-14T14:35:00Z',
  },
  {
    id: 'alt-005',
    deviceId: 'dev-dwc-102',
    deviceName: 'HF-DWC-Beta',
    sensorType: 'dissolvedOxygen',
    severity: 'warning',
    message: 'Dissolved oxygen dropped to 5.7 mg/L. Air pump backup activated.',
    value: 5.7,
    timestamp: '2026-07-13T08:15:00Z',
    resolved: true,
    resolvedAt: '2026-07-13T08:45:00Z',
  },
  {
    id: 'alt-006',
    deviceId: 'dev-nft-101',
    deviceName: 'HF-NFT-Alpha',
    sensorType: 'connection',
    severity: 'critical',
    message: 'Device connection lost. Keep-alive ping failed.',
    timestamp: '2026-07-12T19:30:00Z',
    resolved: true,
    resolvedAt: '2026-07-12T19:42:00Z',
  },
];
